# Generated by Django 5.2.4 on 2025-08-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1st', 'I'), ('2nd', 'II'), ('3rd', 'III'), ('4th', 'IV'), ('5th', 'V'), ('6th', 'VI'), ('7th', 'VII'), ('8th', 'VIII')], max_length=5, unique=True)),
            ],
        ),
    ]
