# Generated by Django 5.2.4 on 2025-07-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_students_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='s_class',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
