# Generated by Django 5.2.4 on 2025-08-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='accounts.roles'),
        ),
    ]
