# Generated by Django 5.2.4 on 2025-08-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_role_teacherprofile_studentprofile'),
        ('acedmics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='course_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='acedmics.courses'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='semester_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='acedmics.semesters'),
        ),
    ]
