# Generated by Django 5.2.4 on 2025-07-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acedmics', '0001_initial'),
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('alternate_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('year', models.CharField(choices=[('1st', 'I'), ('2nd', 'II'), ('3rd', 'III'), ('4th', 'IV')], max_length=10, unique=True)),
                ('address', models.TextField(max_length=200)),
                ('password', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acedmics.courses')),
                ('role', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='admins.roles')),
            ],
        ),
    ]
